{{- with .Values.mxe.credentials }}
{{- if and .user .pwd -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-simple-ml-demo.mxeSecret" $ | quote }}
  labels:
    {{- include "eric-simple-ml-demo.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- include "eric-simple-ml-demo.product-info" $ | nindent 4 }}
type: Opaque
data:
  {{ .userKey }}: {{ .user | b64enc | quote }}
  {{ .pwdKey }}: {{ .pwd | b64enc | quote }}
{{- end }}
{{- end -}}
