apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-simple-ml-demo.name" . }}
  labels:
    {{- include "eric-simple-ml-demo.labels" . | indent 4 }}
  annotations:
    {{- include "eric-simple-ml-demo.product-info" . | indent 4 }}
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/actuator/prometheus'
spec:
  type: ClusterIP
  ports:
    - port: 8050
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "eric-simple-ml-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
