apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-simple-ml-demo.name" . }}-sa
  labels:
    {{- include "eric-simple-ml-demo.labels" . | indent 4 }}
  annotations:
    {{- include "eric-simple-ml-demo.product-info" . | indent 4 }}
automountServiceAccountToken: false
