apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-simple-ml-demo.name" . }}-config
  labels:
    {{- include "eric-simple-ml-demo.labels" . | indent 4 }}
  annotations:
    {{- include "eric-simple-ml-demo.product-info" . | indent 4 }}
data:
  LOG_CTRL_FILE: |-
{{ .Files.Get "files/logcontrol.json" | indent 4}}