apiVersion: v2
name: ${name}
description: Testware for ML Execution Environment Application
type: application
version: ${version}
dependencies:
  - name: eric-sef-exposure-api-manager-client
    import-values:
      - child: exposureApiManagerClient.config
        parent: global.exposureApiManagerClient.config
    repository: https://arm.sero.gic.ericsson.se/artifactory/proj-adp-eric-sef-exposure-api-manager-released-helm/
    version: 1.5.0+27
  - name: eric-simple-ml-demo
    repository: "file://../eric-simple-ml-demo"
    version: ${version}
