apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "eric-oss-ml-platform-app-test.labels" . | nindent 4 }}
spec:
  volumes:
    - name: "{{ .Chart.Name }}-reports"
      emptyDir: {}
    - name: "{{ .Chart.Name }}-logs"
      emptyDir: {}
  containers:
    - name: "{{ $.Chart.Name }}"
      image: {{ $.Values.images.testwareImage | quote }}
      env:
        - name: "APP_VERSION"
          value: {{ $.Values.env.APP_VERSION }}
        - name: "BUILD_URL"
          value: {{ $.Values.env.BUILD_URL }}
        - name: "BUILD_NUMBER"
          value: {{ $.Values.env.BUILD_NUMBER | toString | quote }}
        - name: "STAGING_TYPE"
          value: {{ $.Values.env.STAGING_TYPE }}
        - name: "PRODUCT"
          value: {{ $.Values.env.PRODUCT }}
        - name: "PRODUCT_VERSION"
          value: {{ $.Values.env.PRODUCT_VERSION }}
        - name: "ENVIRONMENT"
          value: {{ $.Values.env.ENVIRONMENT }}
        - name: "SYSTEM_USER"
          value: {{ $.Values.env.SYSTEM_USER }}
        - name: "SYSTEM_USER_PASSWORD"
          value: {{ $.Values.env.SYSTEM_USER_PASSWORD }}
        - name: "GAS_USER"
          value: {{ $.Values.env.GAS_USER }}
        - name : "GAS_PWD"
          value: {{ $.Values.env.GAS_PWD }}
        - name: "GAS_HOSTNAME"
          value: {{ $.Values.env.GAS_HOSTNAME }}
        - name: "EIC_HOSTNAME"
          value: {{ $.Values.env.EIC_HOSTNAME }}
        - name: "APPMGR_HOSTNAME"
          value: {{ $.Values.env.APPMGR_HOSTNAME }}
        - name: "SEF_STATUS"
          value: {{ $.Values.env.SEF_STATUS }}
        - name: "TESTSTAGE"
          value: {{ $.Values.env.TESTSTAGE }}
        - name: "NAMESPACE"
          value: {{ $.Values.env.NAMESPACE }}
        - name: "TESTWARE_NAME"
          value: {{ $.Values.env.TESTWARE_NAME }}
        - name: "ML_ADMIN_USERNAME"
          value: {{ $.Values.env.ML_ADMIN_USERNAME }}
        - name: "ML_ADMIN_PWD"
          value: {{ $.Values.env.ML_ADMIN_PWD }}
        - name: "ML_MODEL_USERNAME"
          value: {{ $.Values.env.ML_MODEL_USERNAME }}
        - name: "ML_MODEL_PWD"
          value: {{ $.Values.env.ML_MODEL_PWD }}
        - name: "IAM_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              name: eric-cncs-oss-config-iam-client-secret
              key: clientSecret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: database_url
        - name: K6_TOOL_GUI_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: gui_url
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: api_url
      volumeMounts:
        - name: "{{ $.Chart.Name }}-reports"
          mountPath: "/reports"
        - name: "{{ .Chart.Name }}-logs"
          mountPath: "/var/log"
      imagePullPolicy: Always
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        runAsNonRoot: false
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: k8s-registry-secret
  schedulerName: default-scheduler
  restartPolicy: Never
  securityContext: {}
  terminationGracePeriodSeconds: 5